### ISSUE TITLE
Feature: add YAML arrays support

### ISSUE THREAD

**Issue by t0pd4wn** [t0pd4wn/yb#2]
At the moment YAML arrays are not supported.

Parsing below ```newArray``` key with ```yb``` will result in only providing the ```this``` value.
```yaml
- newArray: this
arrayChildA: that
arrayChildB: there
```
Output should be closer to:
```yaml
- newArray: this
arrayChildA: that 
arrayChildB: there
```

- [ ] read an array
- [ ] add an array
- [ ] remove an array
